### ISSUE TITLE
sensor respond filetype error

### ISSUE THREAD

**Issue by inteljack** [inteljack/TH_recorder#1]
After a few loops, program fail to read values from DHT
```
Traceback (most recent call last):
  File "th_recorder.py", line 19, in <module>
    th_recorder()
  File "th_recorder.py", line 16, in th_recorder
    print datetime.datetime.now(), 'Temp={0:0.1f}*C  Humidity={1:0.1f}%'.format(temp, humidity)
ValueError: Unknown format code 'f' for object of type 'str'
```

possible issues: filetype of temp and humidity isn't always numbers

**Comment by inteljack** [comment]
file type could be None --> fail to get readings from sensor.
The following fail safe if statement solved the issue:
```
if humidity is None or temp is None:
        time.sleep(2)
        continue
```
